### ISSUE TITLE
How to remove mlops?

### ISSUE THREAD

**Issue by JessKXWL** [FedML-AI/FedML#459]
How to run fedml /python/examples/simulation/MPI locally_ base_ framework_ The code in example, I use readme.md runs. The error in the figure appears. I have deployed the mqtt server locally. I have configured comm in the configuration file_ args.mqtt_ config_ Path, but it doesn't work

![image](https://user-images.githubusercontent.com/33014711/184090035-5c6b3410-e19e-4b3b-8b39-87d06e46b001.png)

How to remove mlops? I set using_mlops: false has no effect

**Comment by chaoyanghe** [comment]
@JessKXWL Please update the code to 0.7.230, it should be fixed.

**Comment by JessKXWL** [comment]
@chaoyanghe Thank you for your advice. Now the problem has been solved. Now my local operation is like this. It seems that I should have finished the training. However, I can't find the trained model and the logs during the operation
![image](https://user-images.githubusercontent.com/33014711/184266334-3678008d-9ef3-4d96-a5d4-000a648decd9.png)
This is the log path I set.
![image](https://user-images.githubusercontent.com/33014711/184266397-a1715475-5668-449f-a529-6186f7d14d5a.png)
![image](https://user-images.githubusercontent.com/33014711/184266607-274046b3-89cb-45c4-87c7-cb088046dad0.png)
![image](https://user-images.githubusercontent.com/33014711/184266548-a32e59ff-8f06-43a3-8425-296d19b391e4.png)
There is no model file in "fedml_client" and "fedml_server".fedml_config.yaml，The log file path in "fedml_config.yaml" does not seem to work.
![image](https://user-images.githubusercontent.com/33014711/184266736-054f83dd-0bd8-4429-bc51-adea2e3a44fe.png)

**Comment by JessKXWL** [comment]
@chaoyanghe I updated fedml to 0.7.230 on CentOS
This is my config file

When I ran this command（`python torch_fedavg_mnist_lr_one_line_example.py --cf fedml_config.yaml`）, an error occurred.
![image](https://user-images.githubusercontent.com/33014711/184268478-2f9cc23f-b54d-4537-91e7-705a5ca8b068.png)
This is the configuration information read by the program.
![image](https://user-images.githubusercontent.com/33014711/184268771-aaafac84-5d90-4ffa-8829-127532b252a0.png)

**Comment by JessKXWL** [comment]
About the trained model I can't find problem
Should we add a "write_sensor_dict_to_mnn" function similar to "python/fedml/cross_device/server_mnn/utils. py" in "python/fedml/cross_silo/client/utils. py", and then call this function at the position on the figure?
![image](https://user-images.githubusercontent.com/33014711/184275660-a73df9ca-4cbf-4291-8ede-4760f86fb72a.png)
![image](https://user-images.githubusercontent.com/33014711/184275706-71ad9977-652e-4609-a684-a9ae9b6ff701.png)

**Comment by alex-liang-kh** [comment]
> @chaoyanghe I updated fedml to 0.7.230 on CentOS This is my config file
> 
> When I ran this command（`python torch_fedavg_mnist_lr_one_line_example.py --cf fedml_config.yaml`）, an error occurred. ![image](https://user-images.githubusercontent.com/33014711/184268478-2f9cc23f-b54d-4537-91e7-705a5ca8b068.png) This is the configuration information read by the program. ![image](https://user-images.githubusercontent.com/33014711/184268771-aaafac84-5d90-4ffa-8829-127532b252a0.png)

Please update the code to 0.7.287, it should be fixed.

**Comment by JessKXWL** [comment]
> > @chaoyanghe I updated fedml to 0.7.230 on CentOS This is my config file
> > When I ran this command（`python torch_fedavg_mnist_lr_one_line_example.py --cf fedml_config.yaml`）, an error occurred. ![image](https://user-images.githubusercontent.com/33014711/184268478-2f9cc23f-b54d-4537-91e7-705a5ca8b068.png) This is the configuration information read by the program. ![image](https://user-images.githubusercontent.com/33014711/184268771-aaafac84-5d90-4ffa-8829-127532b252a0.png)
> 
> Please update the code to 0.7.287, it should be fixed.

Thank you for your advice. But I update the code to  0.7.287. The problem is still unsolved,

**Comment by chaoyanghe** [comment]
@JessKXWL Maybe you should reinstall fedml with the following commands: pip uninstall fedml; pip install fedml, then you may display the fedml version: pip list |grep fedml
