### ISSUE TITLE
ModuleNotFoundError: No module named 'fedml.simulation.mpi.async_fedavg'

### ISSUE THREAD

**Issue by Mirian-Hipolito** [FedML-AI/FedML#488]
Hello, I'm trying to run a basic simulation using MPI but I'm encountering this issue when trying to run from source ..

The script I'm testing is **FedML\python\examples\simulation\mpi_torch_fedavg_mnist_lr_example>**
Python version: Python 3.7.13
FedML version: 0.7.290

![image](https://user-images.githubusercontent.com/94491775/186820949-332faa35-02c6-4042-beb0-57511d59a267.png)

**Comment by chaoyanghe** [comment]
@Mirian-Hipolito Please try the latest version 0.7.298. We've fixed it.

**Comment by Mirian-Hipolito** [comment]
I've updated to the latest version and I'm still facing the same issue, please see the image below

![image](https://user-images.githubusercontent.com/94491775/186931961-1a6aaf37-2eb0-4c14-8619-1ae8fd1f9004.png)

**Comment by chaoyanghe** [comment]
@Mirian-Hipolito Please try our latest version 0.7.300. All examples are bug free. You can refer to our test results at GitHub Actions: https://github.com/FedML-AI/FedML/actions

**Comment by Mirian-Hipolito** [comment]
Working now, thanks! I had to update the Python version to 3.8.10 to the pointed in the  github pipeline .. using 3.7 or 3.8 was throwing the same error.
